### PR TITLE
Add support for SQS event source

### PR DESCRIPTION
**Pull request by theburningmonk**
Addresses #16 which highlights that the plugin is not automatically adding the relevant SQS permissions.

### CODE REVIEW

**Comment by glicht** [comment]
Thanks for submitting this

**Comment by theburningmonk** [comment]
no probs, let me know when you get around to publishing the new version and I'll tell my guys to upgrade as we've had to work around this limitation right now

**Comment by theburningmonk** [comment]
hi @glicht looks like this change was never published to NPM. I understand you're busy with other things these days, I'd like to offer my assistance if you would have me. My team depends on this plugin regularly and we're having to work around limitations like this on a regular basis.

**Comment by glicht** [comment]
Sure. Would be happy to have you involved. I'll do a push to npm in the next days.

**Pull request merged**
